const progress=document.querySelector('.scroll-progress');
const setProgress=()=>{if(!progress)return;const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?scrollY/h*100:0)+'%'};window.addEventListener('scroll',setProgress,{passive:true});setProgress();
document.querySelectorAll('[data-ist-time]').forEach(el=>{const set=()=>{try{el.textContent=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date())+' IST'}catch{el.textContent='IST'}};set();setInterval(set,60000)});
document.querySelectorAll('[data-magnetic]').forEach(el=>{el.addEventListener('mousemove',e=>{if(innerWidth<800)return;const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform=`translate(${x*.08}px,${y*.08}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
const toggle=document.querySelector('.mobile-toggle'),links=document.querySelector('.nav-links');if(toggle&&links){toggle.addEventListener('click',()=>{const open=links.dataset.open==='1';links.dataset.open=open?'0':'1';if(!open){Object.assign(links.style,{display:'flex',position:'absolute',top:'65px',left:'0',right:'0',padding:'18px',background:'rgba(8,12,21,.96)',border:'1px solid rgba(255,255,255,.1)',borderRadius:'16px',flexDirection:'column',boxShadow:'0 20px 50px #0006'})}else links.removeAttribute('style')})}
document.querySelectorAll('.portrait-img').forEach(img=>img.src='/assets/yash-jangid.webp');
document.querySelectorAll('.v2-activity').forEach(grid=>{grid.textContent='';for(let i=0;i<98;i++)grid.appendChild(document.createElement('i'))});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(window.gsap&&window.ScrollTrigger&&!reduced){document.documentElement.classList.add('gsap-ready');gsap.registerPlugin(ScrollTrigger);gsap.set('.reveal',{opacity:0,y:24});gsap.utils.toArray('.reveal').forEach((el,i)=>{gsap.to(el,{opacity:1,y:0,duration:.82,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true},delay:Math.min((i%4)*.03,.1)})});const firstTitle=document.querySelector('.v2-hero h1,.page-hero h1,.case-hero h1');if(firstTitle)gsap.from(firstTitle,{opacity:0,y:34,duration:1,ease:'power3.out',delay:.08});gsap.utils.toArray('.v2-lead,.lead,.page-hero p').slice(0,2).forEach((el,i)=>gsap.from(el,{opacity:0,y:15,duration:.7,ease:'power2.out',delay:.22+i*.08}));const photo=document.querySelector('.v2-photo-frame');if(photo)gsap.from(photo,{opacity:0,scale:.97,x:20,duration:1.02,ease:'power3.out',delay:.16});gsap.from('.v2-float',{opacity:0,y:16,scale:.96,duration:.68,stagger:.09,ease:'back.out(1.35)',delay:.58});const heroPhoto=document.querySelector('.v2-photo');if(heroPhoto)gsap.to(heroPhoto,{yPercent:4,ease:'none',scrollTrigger:{trigger:'.v2-hero',start:'top top',end:'bottom top',scrub:true}});document.querySelectorAll('.v2-project,.v3-work-card').forEach(card=>{const visual=card.querySelector('.v2-project-visual,.v3-work-art');if(visual)gsap.to(visual,{y:-6,ease:'none',scrollTrigger:{trigger:card,start:'top bottom',end:'bottom top',scrub:.7}})});const track=document.querySelector('.v2-stack-track');if(track)gsap.to(track,{xPercent:-50,ease:'none',duration:34,repeat:-1});const orbA=document.querySelector('.v2-orb.a'),orbB=document.querySelector('.v2-orb.b');window.addEventListener('pointermove',e=>{if(innerWidth<900)return;const nx=e.clientX/innerWidth-.5,ny=e.clientY/innerHeight-.5;if(orbA)gsap.to(orbA,{x:nx*38,y:ny*28,duration:1.2,ease:'power2.out'});if(orbB)gsap.to(orbB,{x:nx*-28,y:ny*-20,duration:1.4,ease:'power2.out'})})}else{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el))}
